Use actual bash scripting syntax
multi-py/action-python-versionator pull request #6
Opened 2023-08-08 18:49 UTC by zzkW35

When the 'if' condition doesn't match, the GitHub action workflow stops and the pipeline fails, use proper bash syntax to fix it.

Also update the setup-python action to the latest version.

2023-08-17 13:04 UTC, zzkW35 commented
Bump 😃

2023-08-19 14:08 UTC, tedivm requested changes

2023-08-19 14:08 UTC, tedivm commented on action.yml
> +        then sed -i 's/python_versions:.*/python_versions: [3.8, 3.9, 3.10, 3.11] /' "${{ inputs.action_path }}"; \
Please put the versions in quotes, otherwise yaml can interpret them as numbers which can turn "3.10" into "3.1".

2023-08-30 13:12 UTC, tedivm approved these changes

2023-08-30 13:12 UTC, merged